# imports

In [112]:
import os
from dotenv import load_dotenv
import requests
from bs4 import BeautifulSoup
import pandas as pd
from pathlib import Path
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.support.ui import Select
import time
import datetime

# Part 1

## Cas 1

In [25]:
# Scrap NBA 2022 season league players stats
url = "https://www.basketball-reference.com/leagues/NBA_2022_per_game.html"
response = requests.get(url)
soup = BeautifulSoup(response.content, 'lxml')
target_div = soup.find('div', id='div_per_game_stats')

dataframes = []

if target_div:
    tables = target_div.find_all('table')
    
    for idx, table in enumerate(tables):
        df = pd.read_html(str(table))[0]  
        dataframes.append(df)

    if dataframes:
        combined_df = pd.concat(dataframes, ignore_index=True)
else:
    print("Div not found or no tables inside!")

C:\Users\laien\AppData\Local\Temp\ipykernel_17196\3800751609.py:10: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

In [29]:
# export to csv
# combined_df.to_csv("./data/NBA_2022_per_game.csv")
combined_df

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards
0,1.0,Joel Embiid,27.0,PHI,C,68.0,68.0,33.8,9.8,19.6,...,2.1,9.6,11.7,4.2,1.1,1.5,3.1,2.7,30.6,"MVP-2,AS,NBA2"
1,2.0,LeBron James,37.0,LAL,C,56.0,56.0,37.2,11.4,21.8,...,1.1,7.1,8.2,6.2,1.3,1.1,3.5,2.2,30.3,"MVP-10,AS,NBA3"
2,3.0,Giannis Antetokounmpo,27.0,MIL,PF,67.0,67.0,32.9,10.3,18.6,...,2.0,9.6,11.6,5.8,1.1,1.4,3.3,3.2,29.9,"MVP-3,DPOY-6,AS,NBA1"
3,4.0,Kevin Durant,33.0,BRK,PF,55.0,55.0,37.2,10.5,20.3,...,0.5,6.9,7.4,6.4,0.9,0.9,3.5,2.1,29.9,"MVP-10,AS,NBA2"
4,5.0,Luka Dončić,22.0,DAL,PG,65.0,65.0,35.4,9.9,21.6,...,0.9,8.3,9.1,8.7,1.2,0.6,4.5,2.2,28.4,"MVP-5,AS,NBA1"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
808,602.0,Trayvon Palmer,27.0,DET,SG,1.0,0.0,17.0,0.0,1.0,...,0.0,2.0,2.0,0.0,0.0,0.0,1.0,2.0,0.0,NaN
809,603.0,Emanuel Terry,25.0,PHO,PF,3.0,0.0,6.0,0.0,1.7,...,2.7,2.3,5.0,0.7,0.3,0.0,1.7,1.3,0.0,NaN
810,604.0,Jon Teske,24.0,MEM,C,3.0,0.0,2.7,0.0,0.3,...,0.0,0.7,0.7,0.3,0.3,0.0,0.0,0.3,0.0,NaN
811,605.0,M.J. Walker,23.0,PHO,SG,2.0,0.0,4.0,0.0,2.0,...,0.0,0.5,0.5,0.5,1.0,0.0,0.0,0.5,0.0,NaN
812,NaN,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Cas 2

In [42]:
# Scrap all data
url = "https://content.codecademy.com/courses/beautifulsoup/cacao/index.html"
response = requests.get(url)
soup = BeautifulSoup(response.content, 'lxml')
df=pd.read_html(str(soup))[1]
df.head()

C:\Users\laien\AppData\Local\Temp\ipykernel_17196\1467438252.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df=pd.read_html(str(soup))[1]

,0,1,2,3,4,5,6,7,8
0,Company (Maker-if known),Specific Bean Origin or Bar Name,REF,Review Date,Cocoa Percent,Company Location,Rating,Bean Type,Broad Bean Origin
1,A. Morin,Agua Grande,1876,2016,63%,France,3.75,NaN,Sao Tome
2,A. Morin,Kpime,1676,2015,70%,France,2.75,NaN,Togo
3,A. Morin,Atsane,1676,2015,70%,France,3,NaN,Togo
4,A. Morin,Akata,1680,2015,70%,France,3.5,NaN,Togo

In [52]:
#make filters
col= ['Cocoa  Percent','Rating']
df_filtered = df.loc[1:][[4, 6]]
df_filtered.columns = col

In [56]:
# df_filtered.to_csv("./data/cacao_rating.csv")
# df_filtered.to_json('./data/cas_2/cacao_rating_index.json', orient='index')
# df_filtered.to_json('./data/cas_2/cacao_rating_value.json', orient='values')
# df_filtered.to_json('./data/cas_2/cacao_rating_record.json', orient='records')

"index : Structure les données sous forme de dictionnaire où l'index du DataFrame est inclus."
"records : Structure les données sous forme d'une liste d'enregistrements (dictionnaires), sans l'index."
"values : Retourne uniquement les valeurs sous forme de liste, sans les noms de colonnes ou d'index."

## Cas 3

### Data scraping

In [83]:
#Scrap laptops'data
data={}
for p in range(1,20):
    url=f"https://webscraper.io/test-sites/e-commerce/static/computers/laptops?page={p}"
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')
    for i in soup.find('div', class_='container test-site').find('div', class_='col-lg-9').find_all('div', class_='product-wrapper card-body'):
        title = i.find('a', class_='title').attrs['title']
        description = i.find('p', class_='description').text
        price = i.find('h4', class_='price').text[1:]
        rating = len(i.find('div', class_='ratings').find_all('span', class_='ws-icon ws-icon-star'))
        data[title] = [description,price,rating]
cols = ['title', 'description', 'price','rating']
laptop = pd.DataFrame.from_dict(data, orient='index').reset_index()
laptop.columns = cols
laptop

,title,description,price,rating
0,Packard 255 G2,"15.6"", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows...",416.99,2
1,Aspire E1-510,"15.6"", Pentium N3520 2.16GHz, 4GB, 500GB, Linux",306.99,3
2,ThinkPad T540p,"15.6"", Core i5-4200M, 4GB, 500GB, Win7 Pro 64bit",1178.99,1
3,ProBook,"14"", Core i5 2.6GHz, 4GB, 500GB, Win7 Pro 64bit",739.99,4
4,ThinkPad X240,"12.5"", Core i5-4300U, 8GB, 240GB SSD, Win7 Pro...",1311.99,3
...,...,...,...,...
80,MSI GL62VR 7RFX,"MSI GL62VR 7RFX, 15.6"" FHD, Core i7-7700HQ, 8G...",1299,3
81,Hewlett Packard ProBook 640 G3,"Hewlett Packard ProBook 640 G3, 14"" FHD, Core ...",1326.83,1
82,"Apple MacBook Pro 13"" Space Gray","Apple MacBook Pro 13"" Space Gray, Core i5 2.3G...",1333,1
83,Lenovo ThinkPad T470,"Lenovo ThinkPad T470, 14"" FHD IPS, Core i5-720...",1349.23,1
84,Lenovo ThinkPad Yoga 370 Black,"Lenovo ThinkPad Yoga 370 Black, 13.3"" FHD IPS ...",1362.24,2

### answer questions

In [84]:
#Les 3 laptops les mieux notés.
laptop.sort_values('rating', ascending=False).head(3)

,title,description,price,rating
3,ProBook,"14"", Core i5 2.6GHz, 4GB, 500GB, Win7 Pro 64bit",739.99,4
14,Dell Vostro 15,"Dell Vostro 15 (3568) Black, 15.6"" FHD, Core i...",488.78,4
32,Acer Aspire 3 A315-31 Black,"Acer Aspire 3 A315-31 Black, 15.6"" HD, Pentium...",408.98,4

In [85]:
#Les 3 laptops les moins bien notés
laptop.sort_values('rating', ascending=True).head(3)

,title,description,price,rating
2,ThinkPad T540p,"15.6"", Core i5-4200M, 4GB, 500GB, Win7 Pro 64bit",1178.99,1
5,Aspire E1-572G,"15.6"", Core i5-4200U, 8GB, 1TB, Radeon R7 M265...",581.99,1
7,Pavilion,"15.6"", Core i5-4200U, 6GB, 750GB, Windows 8.1",609.99,1

In [81]:
#Les 3 laptops les plus chers
laptop.sort_values('price', ascending=False).head(3)

,title,description,price,rating
3,ProBook,"14"", Core i5 2.6GHz, 4GB, 500GB, Win7 Pro 64bit",739.99,4
5,Aspire E1-572G,"15.6"", Core i5-4200U, 8GB, 1TB, Radeon R7 M265...",581.99,1
0,Packard 255 G2,"15.6"", AMD E2-3800 1.3GHz, 4GB, 500GB, Windows...",416.99,2

In [82]:
#Les 3 laptops les moins chers
laptop.sort_values('price', ascending=True).head(3)

,title,description,price,rating
2,ThinkPad T540p,"15.6"", Core i5-4200M, 4GB, 500GB, Win7 Pro 64bit",1178.99,1
4,ThinkPad X240,"12.5"", Core i5-4300U, 8GB, 240GB SSD, Win7 Pro...",1311.99,3
1,Aspire E1-510,"15.6"", Pentium N3520 2.16GHz, 4GB, 500GB, Linux",306.99,3

### Data scraping

In [89]:
#Tablets data
data={}
for p in range(1,5):
    url=f"https://webscraper.io/test-sites/e-commerce/static/computers/tablets?page={p}"
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')
    for i in soup.find('div', class_='container test-site').find('div', class_='col-lg-9').find_all('div', class_='product-wrapper card-body'):
        title = i.find('a', class_='title').attrs['title']
        description = i.find('p', class_='description').text
        price = i.find('h4', class_='price').text[1:]
        rating = len(i.find('div', class_='ratings').find_all('span', class_='ws-icon ws-icon-star'))
        data[title] = [description, price, rating]
cols = ['title', 'description', 'price','rating']
tablets = pd.DataFrame.from_dict(data, orient='index').reset_index()
tablets.columns = cols
tablets

,title,description,price,rating
0,Lenovo IdeaTab,"7"" screen, Android",69.99,3
1,Acer Iconia,"7"" screen, Android, 16GB",96.99,1
2,Asus MeMO Pad,"7"" screen, Android, 8GB",102.99,4
3,Amazon Kindle,"6"" screen, wifi",103.99,4
4,iPad Mini Retina,"Wi-Fi + Cellular, 32GB, Silver",537.99,2
5,IdeaTab A3500L,"Black, 7"" IPS, Quad-Core 1.2GHz, 8GB, Android 4.2",88.99,4
6,Galaxy Tab,"16GB, White",251.99,3
7,IdeaTab A3500-H,"Blue, 7"" IPS, Quad-Core 1.3GHz, 8GB, 3G, Andro...",148.99,2
8,Galaxy Tab 3,"7"", 8GB, Wi-Fi, Android 4.2, Yellow",107.99,2
9,Galaxy Note,"10.1"", 3G, Android 4.0, Garnet Red",399.99,4
10,MeMO Pad 7,"White, 7"", Atom 1.2GHz, 8GB, Android 4.4",130.99,1
11,Galaxy Tab 4,"LTE (SM-T235), Quad-Core 1.2GHz, 8GB, Black",233.99,4
12,Memo Pad HD 7,"IPS, Dual-Core 1.2GHz, 8GB, Android 4.3",101.99,2
13,Galaxy Note 10.1,"10.1"", 32GB, Black",587.99,2
14,MeMo PAD FHD 10,"White, 10.1"" IPS, 1.6GHz, 2GB, 16GB, Android 4.2",320.99,2
15,IdeaTab S5000,"Silver, 7"" IPS, Quad-Core 1.2Ghz, 16GB, 3G, An...",172.99,3
16,Iconia B1-730HD,"Black, 7"", 1.6GHz Dual-Core, 8GB, Android 4.4",99.99,3
17,IdeaTab A8-50,"Blue, 8"" IPS, Quad-Core 1.3GHz, 16GB, Android 4.2",121.99,2
18,Apple iPad Air,"Wi-Fi, 64GB, Silver",603.99,3

repeat same steps with tablets dataframe

# Selenium

In [105]:
# Create extraction function
def extract_info_selenium(url: str, country: str = 'France', season: str = '23/24') -> dict:
    # Set up Selenium options
    firefox_options = Options()
    firefox_options.add_argument("--headless")  # Run headless Firefox
    firefox_options.add_argument("--no-sandbox")
    firefox_options.add_argument("--disable-dev-shm-usage")
    firefox_options.set_preference("general.useragent.override", 
                                    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3")
    
    # Initialize the WebDriver
    driver = webdriver.Firefox(options=firefox_options)
    
    try:
        driver.get(url)
        
        # Set selectionables
        driver.find_element(By.XPATH, "//home-away-selector//div[@class='btn-group-wrap']//label[text()='All matches']").click()
        
        # Select country
        country_dropdown = Select(driver.find_element(By.ID, 'country'))
        country_dropdown.select_by_visible_text(country)
        time.sleep(2)  # Allow time for the page to load

        # Select season
        season_dropdown = Select(driver.find_element(By.ID, 'season'))
        season_dropdown.select_by_visible_text(season)
        time.sleep(2)  # Allow time for the page to load
        
        # Fetch data
        matches = driver.find_elements(By.TAG_NAME, 'tr')
        match_list = [match.text for match in matches]
    
    finally:
        driver.quit()
    
    return match_list

In [106]:
url= 'https://www.adamchoi.co.uk/teamgoals/detailed'
r=extract_info_selenium(url)
len(r)

# API

In [113]:
if load_dotenv():
    API_KEY = os.getenv("open_weather_apikey")
else:
    print('cant find any open weather api key')
    exit()

## Custom functions

In [117]:
from typing import Optional

def coordinate_retrieve(city_name: str, api_key: str = API_KEY) -> Optional[tuple]:
    url = "https://api.openweathermap.org/geo/1.0/direct"

    params = {"q": city_name,
              "appid": api_key,
              "lang": "en",
              'limit': 1}
    try:
        response = requests.get(url, params=params).json()
        return response[0]['lat'], response[0]['lon']
    except Exception as e:
        return (e.args[0])

In [118]:
def get_current_weather(city_name, api_key: str = API_KEY) -> Optional[
    str]:
    # latitude,longitude = coordinate_retrieve(city_name, api_key)
    url = "https://api.openweathermap.org/data/2.5/weather"
    params = {
        'q': city_name,
        'appid': api_key,
        'units': 'metric',  # pour obtenir les données en degrés Celsius
        'lang': 'fr'
    }

    response = requests.get(url, params=params)

    if response.status_code == 200:
        data = response.json()
        weather = {
            'city': data['name'],
            'temperature': data['main']['temp'],
            'temp_min': data['main']['temp_min'],
            'temp_max': data['main']['temp_max'],
            'description': data['weather'][0]['description'],
            'humidity': data['main']['humidity'],
            'pressure': data['main']['pressure'],
            'wind_speed': data['wind']['speed'],
            'local_time': str(datetime.datetime.fromtimestamp(data['dt']).astimezone(
                datetime.timezone(datetime.timedelta(seconds=data['timezone']))))
        }
        return weather
    else:
        return None

In [119]:
def weather_over5(city_name, api_key: str = API_KEY) -> Optional[
    pd.DataFrame]:
    url = "https://api.openweathermap.org/data/2.5/forecast"
    params = {
        'q': city_name,
        'appid': api_key,
        'units': 'metric',  # pour obtenir les données en degrés Celsius
        'lang': 'fr'
    }

    response = requests.get(url, params=params)

    if response.status_code == 200:
        data = response.json()
        result = []
        for item in data['list']:
            weather = {
                'city': data['city']['name'],
                'temperature': item['main']['temp'],
                'temp_min': item['main']['temp_min'],
                'temp_max': item['main']['temp_max'],
                'weather': item['weather'][0]['description'],
                'humidity': item['main']['humidity'],
                'pressure': item['main']['pressure'],
                'wind_speed': item['wind']['speed'],
                'local_time': str(datetime.datetime.fromtimestamp(item['dt']).astimezone(
                    datetime.timezone(datetime.timedelta(seconds=data['city']['timezone']))))
            }
            result.append(weather)
        return pd.DataFrame.from_dict(result)
    else:
        return None

## API CAll examples

### Single weather data API call

In [120]:
weather = get_current_weather('Paris')
if weather:
    print(f"Weather in {weather['city']}:")
    print(f"Temperature: {weather['temperature']}°C")
    print(f"Description: {weather['description']}")
    print(f"Humidity: {weather['humidity']}%")
    print(f"Pressure: {weather['pressure']} hPa")
    print(f"Wind Speed: {weather['wind_speed']} m/s")
else:
    print("Failed to get weather data")

Weather in Paris:
Temperature: 12.54°C
Description: ciel dégagé
Humidity: 97%
Pressure: 1015 hPa
Wind Speed: 2.57 m/s

### 5 day / 3 hours weather forecast

In [121]:
weather_over5('Paris')

,city,temperature,temp_min,temp_max,weather,humidity,pressure,wind_speed,local_time
0,Paris,13.04,13.04,14.13,légère pluie,93,1015,2.68,2024-10-25 08:00:00+02:00
1,Paris,14.24,14.24,15.11,nuageux,83,1016,2.81,2024-10-25 11:00:00+02:00
2,Paris,17.42,17.42,17.42,couvert,70,1017,3.35,2024-10-25 14:00:00+02:00
3,Paris,15.94,15.94,15.94,légère pluie,85,1017,2.15,2024-10-25 17:00:00+02:00
4,Paris,15.89,15.89,15.89,couvert,87,1018,1.73,2024-10-25 20:00:00+02:00
5,Paris,15.35,15.35,15.35,couvert,91,1018,0.38,2024-10-25 23:00:00+02:00
6,Paris,14.87,14.87,14.87,légère pluie,92,1017,1.20,2024-10-26 02:00:00+02:00
7,Paris,14.28,14.28,14.28,légère pluie,91,1016,2.48,2024-10-26 05:00:00+02:00
8,Paris,13.54,13.54,13.54,couvert,94,1015,1.82,2024-10-26 08:00:00+02:00
9,Paris,15.39,15.39,15.39,nuageux,82,1016,2.31,2024-10-26 11:00:00+02:00
10,Paris,17.32,17.32,17.32,nuageux,76,1015,1.31,2024-10-26 14:00:00+02:00
11,Paris,17.72,17.72,17.72,couvert,75,1014,1.01,2024-10-26 17:00:00+02:00
12,Paris,16.10,16.10,16.10,légère pluie,84,1016,0.77,2024-10-26 20:00:00+02:00
13,Paris,15.71,15.71,15.71,légère pluie,88,1016,1.52,2024-10-26 23:00:00+02:00
14,Paris,15.01,15.01,15.01,légère pluie,91,1017,1.51,2024-10-27 02:00:00+02:00
15,Paris,14.80,14.80,14.80,couvert,92,1018,1.54,2024-10-27 05:00:00+02:00
16,Paris,14.54,14.54,14.54,couvert,93,1020,1.88,2024-10-27 08:00:00+02:00
17,Paris,15.62,15.62,15.62,couvert,87,1022,1.96,2024-10-27 11:00:00+02:00
18,Paris,17.84,17.84,17.84,couvert,75,1023,1.67,2024-10-27 14:00:00+02:00
19,Paris,18.23,18.23,18.23,couvert,70,1023,1.88,2024-10-27 17:00:00+02:00
20,Paris,17.08,17.08,17.08,couvert,78,1025,1.98,2024-10-27 20:00:00+02:00
21,Paris,15.60,15.60,15.60,partiellement nuageux,85,1026,1.11,2024-10-27 23:00:00+02:00
22,Paris,14.66,14.66,14.66,peu nuageux,89,1026,0.57,2024-10-28 02:00:00+02:00
23,Paris,13.96,13.96,13.96,ciel dégagé,91,1026,0.89,2024-10-28 05:00:00+02:00
24,Paris,13.48,13.48,13.48,partiellement nuageux,94,1026,0.91,2024-10-28 08:00:00+02:00
25,Paris,14.95,14.95,14.95,couvert,81,1027,0.62,2024-10-28 11:00:00+02:00
26,Paris,17.73,17.73,17.73,couvert,64,1026,1.16,2024-10-28 14:00:00+02:00
27,Paris,18.53,18.53,18.53,couvert,60,1025,1.12,2024-10-28 17:00:00+02:00
28,Paris,16.80,16.80,16.80,couvert,70,1026,1.32,2024-10-28 20:00:00+02:00
29,Paris,15.51,15.51,15.51,couvert,76,1026,0.58,2024-10-28 23:00:00+02:00
30,Paris,14.76,14.76,14.76,couvert,81,1026,0.39,2024-10-29 02:00:00+02:00
31,Paris,14.29,14.29,14.29,nuageux,83,1026,0.48,2024-10-29 05:00:00+02:00
32,Paris,13.61,13.61,13.61,partiellement nuageux,87,1026,0.35,2024-10-29 08:00:00+02:00
33,Paris,15.40,15.40,15.40,ciel dégagé,75,1027,0.96,2024-10-29 11:00:00+02:00
34,Paris,18.31,18.31,18.31,peu nuageux,60,1026,0.62,2024-10-29 14:00:00+02:00
35,Paris,19.12,19.12,19.12,partiellement nuageux,55,1026,1.20,2024-10-29 17:00:00+02:00
36,Paris,17.26,17.26,17.26,peu nuageux,66,1026,1.60,2024-10-29 20:00:00+02:00
37,Paris,15.52,15.52,15.52,ciel dégagé,78,1027,1.88,2024-10-29 23:00:00+02:00
38,Paris,14.40,14.40,14.40,ciel dégagé,83,1027,1.52,2024-10-30 02:00:00+02:00
39,Paris,13.56,13.56,13.56,ciel dégagé,85,1026,1.66,2024-10-30 05:00:00+02:00

In [122]:
weather_over5('Shanghai')

,city,temperature,temp_min,temp_max,weather,humidity,pressure,wind_speed,local_time
0,Shanghai,22.74,22.39,22.74,couvert,66,1019,4.71,2024-10-25 14:00:00+08:00
1,Shanghai,22.38,22.11,22.38,couvert,74,1019,4.13,2024-10-25 17:00:00+08:00
2,Shanghai,21.64,21.64,21.64,couvert,84,1019,3.99,2024-10-25 20:00:00+08:00
3,Shanghai,21.76,21.76,21.76,couvert,86,1018,4.19,2024-10-25 23:00:00+08:00
4,Shanghai,21.55,21.55,21.55,légère pluie,90,1017,4.19,2024-10-26 02:00:00+08:00
5,Shanghai,21.41,21.41,21.41,légère pluie,93,1016,4.30,2024-10-26 05:00:00+08:00
6,Shanghai,21.34,21.34,21.34,légère pluie,92,1017,4.47,2024-10-26 08:00:00+08:00
7,Shanghai,21.35,21.35,21.35,légère pluie,93,1017,4.30,2024-10-26 11:00:00+08:00
8,Shanghai,21.64,21.64,21.64,légère pluie,93,1015,3.77,2024-10-26 14:00:00+08:00
9,Shanghai,21.66,21.66,21.66,légère pluie,97,1014,1.98,2024-10-26 17:00:00+08:00
10,Shanghai,21.92,21.92,21.92,légère pluie,95,1016,3.79,2024-10-26 20:00:00+08:00
11,Shanghai,21.46,21.46,21.46,légère pluie,94,1015,2.56,2024-10-26 23:00:00+08:00
12,Shanghai,21.07,21.07,21.07,pluie modérée,98,1014,1.36,2024-10-27 02:00:00+08:00
13,Shanghai,20.72,20.72,20.72,pluie modérée,96,1014,2.16,2024-10-27 05:00:00+08:00
14,Shanghai,20.88,20.88,20.88,légère pluie,97,1015,2.66,2024-10-27 08:00:00+08:00
15,Shanghai,20.36,20.36,20.36,légère pluie,94,1014,3.98,2024-10-27 11:00:00+08:00
16,Shanghai,19.60,19.60,19.60,légère pluie,91,1013,4.25,2024-10-27 14:00:00+08:00
17,Shanghai,19.25,19.25,19.25,légère pluie,88,1014,4.40,2024-10-27 17:00:00+08:00
18,Shanghai,18.58,18.58,18.58,légère pluie,90,1016,3.41,2024-10-27 20:00:00+08:00
19,Shanghai,17.74,17.74,17.74,pluie modérée,90,1017,3.65,2024-10-27 23:00:00+08:00
20,Shanghai,17.01,17.01,17.01,légère pluie,85,1016,2.45,2024-10-28 02:00:00+08:00
21,Shanghai,17.35,17.35,17.35,couvert,84,1016,2.05,2024-10-28 05:00:00+08:00
22,Shanghai,17.86,17.86,17.86,couvert,78,1017,2.64,2024-10-28 08:00:00+08:00
23,Shanghai,21.01,21.01,21.01,couvert,59,1017,3.85,2024-10-28 11:00:00+08:00
24,Shanghai,20.63,20.63,20.63,couvert,57,1016,4.58,2024-10-28 14:00:00+08:00
25,Shanghai,18.51,18.51,18.51,couvert,59,1017,3.58,2024-10-28 17:00:00+08:00
26,Shanghai,16.96,16.96,16.96,couvert,65,1018,2.74,2024-10-28 20:00:00+08:00
27,Shanghai,16.29,16.29,16.29,couvert,67,1018,1.98,2024-10-28 23:00:00+08:00
28,Shanghai,15.74,15.74,15.74,couvert,69,1017,1.95,2024-10-29 02:00:00+08:00
29,Shanghai,15.25,15.25,15.25,couvert,72,1017,1.85,2024-10-29 05:00:00+08:00
30,Shanghai,17.00,17.00,17.00,couvert,64,1018,2.44,2024-10-29 08:00:00+08:00
31,Shanghai,19.93,19.93,19.93,couvert,48,1018,2.37,2024-10-29 11:00:00+08:00
32,Shanghai,21.07,21.07,21.07,nuageux,41,1016,3.56,2024-10-29 14:00:00+08:00
33,Shanghai,19.19,19.19,19.19,partiellement nuageux,51,1017,3.30,2024-10-29 17:00:00+08:00
34,Shanghai,16.98,16.98,16.98,peu nuageux,62,1018,2.80,2024-10-29 20:00:00+08:00
35,Shanghai,16.15,16.15,16.15,partiellement nuageux,69,1019,1.48,2024-10-29 23:00:00+08:00
36,Shanghai,15.60,15.60,15.60,partiellement nuageux,74,1018,2.21,2024-10-30 02:00:00+08:00
37,Shanghai,16.11,16.11,16.11,couvert,75,1019,2.53,2024-10-30 05:00:00+08:00
38,Shanghai,18.06,18.06,18.06,couvert,75,1020,2.68,2024-10-30 08:00:00+08:00
39,Shanghai,21.32,21.32,21.32,couvert,69,1019,3.40,2024-10-30 11:00:00+08:00

In [123]:
weather_over5('Toronto')

,city,temperature,temp_min,temp_max,weather,humidity,pressure,wind_speed,local_time
0,Toronto,5.76,5.76,9.65,peu nuageux,46,1022,1.30,2024-10-25 02:00:00-04:00
1,Toronto,7.47,7.47,9.29,partiellement nuageux,54,1021,1.56,2024-10-25 05:00:00-04:00
2,Toronto,8.98,8.98,8.98,nuageux,63,1021,1.18,2024-10-25 08:00:00-04:00
3,Toronto,10.02,10.02,10.02,couvert,49,1020,2.22,2024-10-25 11:00:00-04:00
4,Toronto,10.73,10.73,10.73,légère pluie,59,1018,1.71,2024-10-25 14:00:00-04:00
5,Toronto,10.93,10.93,10.93,légère pluie,68,1017,1.77,2024-10-25 17:00:00-04:00
6,Toronto,11.07,11.07,11.07,légère pluie,78,1017,2.53,2024-10-25 20:00:00-04:00
7,Toronto,9.96,9.96,9.96,partiellement nuageux,85,1017,3.63,2024-10-25 23:00:00-04:00
8,Toronto,9.73,9.73,9.73,partiellement nuageux,75,1018,4.92,2024-10-26 02:00:00-04:00
9,Toronto,8.36,8.36,8.36,ciel dégagé,67,1020,5.28,2024-10-26 05:00:00-04:00
10,Toronto,7.96,7.96,7.96,ciel dégagé,61,1022,4.71,2024-10-26 08:00:00-04:00
11,Toronto,10.37,10.37,10.37,peu nuageux,52,1024,5.17,2024-10-26 11:00:00-04:00
12,Toronto,12.48,12.48,12.48,partiellement nuageux,29,1023,6.15,2024-10-26 14:00:00-04:00
13,Toronto,11.65,11.65,11.65,ciel dégagé,30,1025,5.58,2024-10-26 17:00:00-04:00
14,Toronto,8.67,8.67,8.67,partiellement nuageux,39,1028,4.69,2024-10-26 20:00:00-04:00
15,Toronto,7.54,7.54,7.54,couvert,43,1029,3.49,2024-10-26 23:00:00-04:00
16,Toronto,6.65,6.65,6.65,nuageux,46,1029,2.42,2024-10-27 02:00:00-04:00
17,Toronto,5.79,5.79,5.79,partiellement nuageux,51,1029,2.40,2024-10-27 05:00:00-04:00
18,Toronto,5.13,5.13,5.13,partiellement nuageux,57,1030,2.90,2024-10-27 08:00:00-04:00
19,Toronto,8.75,8.75,8.75,peu nuageux,47,1030,3.61,2024-10-27 11:00:00-04:00
20,Toronto,12.61,12.61,12.61,partiellement nuageux,31,1027,3.64,2024-10-27 14:00:00-04:00
21,Toronto,13.48,13.48,13.48,partiellement nuageux,29,1026,3.21,2024-10-27 17:00:00-04:00
22,Toronto,11.22,11.22,11.22,partiellement nuageux,38,1027,1.85,2024-10-27 20:00:00-04:00
23,Toronto,9.41,9.41,9.41,ciel dégagé,40,1028,1.51,2024-10-27 23:00:00-04:00
24,Toronto,8.44,8.44,8.44,peu nuageux,37,1028,0.93,2024-10-28 02:00:00-04:00
25,Toronto,7.94,7.94,7.94,peu nuageux,45,1028,0.39,2024-10-28 05:00:00-04:00
26,Toronto,7.59,7.59,7.59,partiellement nuageux,59,1029,0.37,2024-10-28 08:00:00-04:00
27,Toronto,10.71,10.71,10.71,nuageux,55,1029,1.64,2024-10-28 11:00:00-04:00
28,Toronto,12.81,12.81,12.81,nuageux,50,1027,2.65,2024-10-28 14:00:00-04:00
29,Toronto,12.67,12.67,12.67,couvert,47,1026,3.31,2024-10-28 17:00:00-04:00
30,Toronto,11.76,11.76,11.76,couvert,63,1026,3.33,2024-10-28 20:00:00-04:00
31,Toronto,11.50,11.50,11.50,couvert,71,1025,2.31,2024-10-28 23:00:00-04:00
32,Toronto,10.74,10.74,10.74,nuageux,75,1024,2.05,2024-10-29 02:00:00-04:00
33,Toronto,10.45,10.45,10.45,partiellement nuageux,90,1023,2.04,2024-10-29 05:00:00-04:00
34,Toronto,10.96,10.96,10.96,partiellement nuageux,90,1022,2.68,2024-10-29 08:00:00-04:00
35,Toronto,13.66,13.66,13.66,légère pluie,81,1021,4.27,2024-10-29 11:00:00-04:00
36,Toronto,18.71,18.71,18.71,couvert,62,1019,5.02,2024-10-29 14:00:00-04:00
37,Toronto,18.74,18.74,18.74,couvert,65,1019,4.46,2024-10-29 17:00:00-04:00
38,Toronto,18.40,18.40,18.40,couvert,69,1020,3.64,2024-10-29 20:00:00-04:00
39,Toronto,18.54,18.54,18.54,couvert,68,1020,4.94,2024-10-29 23:00:00-04:00

# Comparaison des Méthodes et Conclusion

En tant que simple exécutant, je me charge d'exécuter sans me poser de question ! (ceci dit voici une proposition de réponses)
Quand utiliser ces outils ?

## Quand utiliser ces outils ?
- **BeautifulSoup**: 
  - Utilisé principalement pour extraire des données de fichiers HTML et XML. 
  - Idéal pour des pages statiques où le contenu ne change pas dynamiquement. 
  - Bon choix lorsque l'on a déjà le contenu HTML (par exemple, via une requête HTTP).

- **Selenium**: 
  - Utile pour interagir avec des pages web dynamiques qui utilisent JavaScript pour charger le contenu.
  - Permet d'automatiser les actions sur le navigateur (clics, remplissage de formulaires, etc.).
  - Utilisé lorsque les données sont chargées après le rendu initial de la page, comme les applications web modernes.

- **API Call**: 
  - Idéal lorsque le site web propose une API publique ou privée.
  - Permet d'accéder directement aux données sous une forme structurée (JSON, XML), souvent plus efficace et moins sujet à des restrictions légales.
  - Utilisé pour éviter le scraping en cas d'API disponible qui fournit les données nécessaires.

## Limites ?
- **BeautifulSoup**: 
  - Ne gère pas l'exécution de JavaScript, ce qui peut limiter son utilisation pour des pages web dynamiques.
  - Nécessite souvent un prétraitement pour obtenir le contenu HTML, ce qui peut nécessiter d'autres outils comme `requests`.

- **Selenium**: 
  - Plus lourd en ressources, car il nécessite un navigateur pour fonctionner. Cela peut rendre le scraping plus lent.
  - La configuration et la maintenance peuvent être plus complexes, surtout avec différents navigateurs et versions.

- **API Call**: 
  - Limité à ce que l'API expose. Certaines données peuvent ne pas être disponibles ou peuvent être soumises à des quotas d'utilisation.
  - Nécessite des connaissances sur la documentation de l'API, et les modifications de l'API peuvent casser le code existant.

## Éthiques du scraping
- **Respect des conditions d'utilisation**: Toujours lire et respecter les conditions d'utilisation des sites web. Certaines pages interdisent explicitement le scraping.
- **Impact sur le serveur**: Un scraping agressif peut surcharger le serveur du site web, affectant ainsi son fonctionnement. Il est donc essentiel de limiter le taux de requêtes (throttling).
- **Attribution des sources**: Si vous utilisez des données d'un site, il est souvent éthique de donner crédit à la source.

## Gestion des données personnelles et confidentialité
- **Respect de la vie privée**: Ne pas collecter de données personnelles sans le consentement explicite des utilisateurs. Cela inclut les informations identifiables comme les noms, adresses e-mail, etc.
- **Règlementations**: Se conformer aux lois en vigueur sur la protection des données (comme le RGPD en Europe) qui réglementent la collecte et le traitement des données personnelles.
- **Anonymisation des données**: Si des données personnelles sont collectées, envisager des méthodes d'anonymisation pour protéger l'identité des utilisateurs.